task-3 - implementation
klimashevsky-pavel/NodeJS-GMP2018Q4 pull request #3
Opened 2019-01-21 17:47 UTC by klimashevsky-pavel

task: https://epam-my.sharepoint.com/personal/vitali_kozlov_epam_com/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fvitali_kozlov_epam_com%2FDocuments%2FNode%2Ejs%2FCDP%2FHomeworks%2F3%2E%20Command%20Line%2E%20Debugging%2E%20Errors%20handling%20-%20Filesystem%20and%20Streams%2FHomework%203%2Epdf&parent=%2Fpersonal%2Fvitali_kozlov_epam_com%2FDocuments%2FNode%2Ejs%2FCDP%2FHomeworks%2F3%2E%20Command%20Line%2E%20Debugging%2E%20Errors%20handling%20-%20Filesystem%20and%20Streams&slrid=c9ceb79e-f06e-7000-9a33-de546d2a47ad
Found some issues during spliting to modules without bundling, for more info DM me

2019-01-21 19:13 UTC, deser commented on src/utils/streams/stream.ts
> +    const stringUpperCase = chunkString.toUpperCase();
code duplicate with reverseStringData

2019-01-21 19:14 UTC, deser commented on src/utils/streams/stream.ts
> +    process.exit();
but the name of the method doesn't say me that it will terminate process :)

2019-01-21 19:18 UTC, deser commented on src/utils/streams/stream.ts
> +        multistream(cssReadStreams).pipe(fs.createWriteStream(bundleCssPath));
shouldn't this be outside `fs.readdir`?

2019-01-21 19:18 UTC, deser commented on src/utils/streams/stream.ts
> +main();
hello, C++!

2019-01-21 19:19 UTC, deser requested changes
Tests and split streams.ts into modules

2019-02-03 12:13 UTC, klimashevsky-pavel commented
Sorry, no time for splitting :))

2019-02-03 12:13 UTC, merged